version: 2.1

commands:
  print_pipeline_id:
    description: "A simple command for printing the Circle CI Workflow ID from its environment variable named $CIRCLE_WORKFLOW_ID to the console"
    parameters:
      to:
        type: string
        default: "Hello commands"
    steps:
      - run: echo << parameters.to >>    

jobs:
  print_pipelineID:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id:
          to: $CIRCLE_WORKFLOW_ID

workflows:
  Reusable-Commands:
    jobs:
      - print_pipelineID
