version: 2.1

commands:
  print_pipeline_id:
    description: "Print Circle workflow id"
    parameters:
      to:
        type: string
        default: ${CIRCLE_WORKFLOW_ID}
    steps:
      - run: echo << parameters.to >>

jobs:
  my_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id:
          to: "Print other stuff"

workflows:
  my_workflow:
    jobs:
      - my_job